version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-log-retention"
s3_bucket = "<REPLACE_ME>"
s3_prefix = "lambda-log-retention"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
